FROM registry.access.redhat.com/ubi9/python-312:9.7

ENV SUMMARY="Demo MCP server" \
    DESCRIPTION="Demo MCP server prodiving access to /proc/cpuinfo from a node."

LABEL name="demo-mcp-server" \
      summary="${SUMMARY}" \
      description="${DESCRIPTION}" \
      io.k8s.display-name="demo-mcp-server" \
      io.k8s.description="${DESCRIPTION}" \
      io.openshift.tags="mcp,python"

# Install requirements
COPY --chown=1001:0 requirements.txt /opt/app/requirements.txt
WORKDIR /opt/app
RUN pip install --no-cache-dir -r requirements.txt

# Copy server
COPY --chown=1001:0 demomcp.py /opt/app/demomcp.py

EXPOSE 9028

WORKDIR /opt/app
ENTRYPOINT ["python", "demomcp.py"]
